export interface SubjectTopic {
  id: string;
  name: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
  topics: SubjectTopic[];
}

export const subjects: Subject[] = [
  {
    id: 'sat',
    name: 'SAT',
    icon: 'school',
    color: '#6C5CE7',
    topics: [
      { id: 'sat-reading', name: 'Reading Comprehension' },
      { id: 'sat-writing', name: 'Writing & Language' },
      { id: 'sat-math-no-calc', name: 'Math (No Calculator)' },
      { id: 'sat-math-calc', name: 'Math (Calculator)' },
      { id: 'sat-grammar', name: 'Grammar & Usage' },
      { id: 'sat-vocabulary', name: 'Vocabulary in Context' },
      { id: 'sat-data-analysis', name: 'Data Analysis' },
      { id: 'sat-algebra', name: 'Heart of Algebra' },
      { id: 'sat-advanced-math', name: 'Passport to Advanced Math' },
    ],
  },
  {
    id: 'act',
    name: 'ACT',
    icon: 'school',
    color: '#E84393',
    topics: [
      { id: 'act-english', name: 'English' },
      { id: 'act-math', name: 'Mathematics' },
      { id: 'act-reading', name: 'Reading' },
      { id: 'act-science', name: 'Science' },
      { id: 'act-writing', name: 'Writing (Essay)' },
    ],
  },
  {
    id: 'ap-biology',
    name: 'AP Biology',
    icon: 'leaf',
    color: '#00B894',
    topics: [
      { id: 'ap-bio-cells', name: 'Cell Structure & Function' },
      { id: 'ap-bio-genetics', name: 'Genetics & Heredity' },
      { id: 'ap-bio-evolution', name: 'Evolution & Natural Selection' },
      { id: 'ap-bio-ecology', name: 'Ecology' },
      { id: 'ap-bio-molecular', name: 'Molecular Biology' },
      { id: 'ap-bio-physiology', name: 'Animal Physiology' },
      { id: 'ap-bio-plants', name: 'Plant Biology' },
    ],
  },
  {
    id: 'ap-chemistry',
    name: 'AP Chemistry',
    icon: 'flask',
    color: '#00CEC9',
    topics: [
      { id: 'ap-chem-atomic', name: 'Atomic Structure' },
      { id: 'ap-chem-bonding', name: 'Chemical Bonding' },
      { id: 'ap-chem-reactions', name: 'Chemical Reactions' },
      { id: 'ap-chem-kinetics', name: 'Kinetics' },
      { id: 'ap-chem-thermo', name: 'Thermodynamics' },
      { id: 'ap-chem-equilibrium', name: 'Equilibrium' },
      { id: 'ap-chem-acids', name: 'Acids & Bases' },
    ],
  },
  {
    id: 'ap-physics-1',
    name: 'AP Physics 1',
    icon: 'atom',
    color: '#0984E3',
    topics: [
      { id: 'ap-phys1-kinematics', name: 'Kinematics' },
      { id: 'ap-phys1-dynamics', name: 'Dynamics (Forces)' },
      { id: 'ap-phys1-energy', name: 'Energy & Work' },
      { id: 'ap-phys1-momentum', name: 'Momentum' },
      { id: 'ap-phys1-rotation', name: 'Rotational Motion' },
      { id: 'ap-phys1-waves', name: 'Waves & Sound' },
      { id: 'ap-phys1-circuits', name: 'Simple Circuits' },
    ],
  },
  {
    id: 'ap-us-history',
    name: 'AP US History',
    icon: 'flag',
    color: '#D63031',
    topics: [
      { id: 'ap-ush-colonial', name: 'Colonial America' },
      { id: 'ap-ush-revolution', name: 'American Revolution' },
      { id: 'ap-ush-constitution', name: 'Constitution & Early Republic' },
      { id: 'ap-ush-civil-war', name: 'Civil War & Reconstruction' },
      { id: 'ap-ush-gilded', name: 'Gilded Age & Progressive Era' },
      { id: 'ap-ush-wwi-wwii', name: 'World Wars' },
      { id: 'ap-ush-cold-war', name: 'Cold War Era' },
      { id: 'ap-ush-modern', name: 'Modern America' },
    ],
  },
  {
    id: 'ap-world-history',
    name: 'AP World History',
    icon: 'globe',
    color: '#E17055',
    topics: [
      { id: 'ap-wh-ancient', name: 'Ancient Civilizations' },
      { id: 'ap-wh-classical', name: 'Classical Era' },
      { id: 'ap-wh-medieval', name: 'Medieval Period' },
      { id: 'ap-wh-early-modern', name: 'Early Modern Period' },
      { id: 'ap-wh-industrialization', name: 'Industrialization' },
      { id: 'ap-wh-modern', name: 'Modern Era' },
    ],
  },
  {
    id: 'ap-psychology',
    name: 'AP Psychology',
    icon: 'brain',
    color: '#A29BFE',
    topics: [
      { id: 'ap-psych-bio', name: 'Biological Bases of Behavior' },
      { id: 'ap-psych-sensation', name: 'Sensation & Perception' },
      { id: 'ap-psych-learning', name: 'Learning & Memory' },
      { id: 'ap-psych-cognition', name: 'Cognition' },
      { id: 'ap-psych-development', name: 'Developmental Psychology' },
      { id: 'ap-psych-abnormal', name: 'Abnormal Psychology' },
      { id: 'ap-psych-social', name: 'Social Psychology' },
    ],
  },
  {
    id: 'ap-english-lang',
    name: 'AP English Language',
    icon: 'book',
    color: '#FDCB6E',
    topics: [
      { id: 'ap-eng-rhetoric', name: 'Rhetorical Analysis' },
      { id: 'ap-eng-argument', name: 'Argumentation' },
      { id: 'ap-eng-synthesis', name: 'Synthesis' },
      { id: 'ap-eng-style', name: 'Style & Tone' },
    ],
  },
  {
    id: 'ap-calculus-ab',
    name: 'AP Calculus AB',
    icon: 'calculator',
    color: '#74B9FF',
    topics: [
      { id: 'ap-calc-limits', name: 'Limits & Continuity' },
      { id: 'ap-calc-derivatives', name: 'Derivatives' },
      { id: 'ap-calc-integrals', name: 'Integrals' },
      { id: 'ap-calc-applications', name: 'Applications of Derivatives' },
      { id: 'ap-calc-ftc', name: 'Fundamental Theorem of Calculus' },
    ],
  },
  {
    id: 'algebra-1',
    name: 'Algebra 1',
    icon: 'calculator',
    color: '#0984E3',
    topics: [
      { id: 'alg1-linear', name: 'Linear Equations' },
      { id: 'alg1-inequalities', name: 'Inequalities' },
      { id: 'alg1-systems', name: 'Systems of Equations' },
      { id: 'alg1-polynomials', name: 'Polynomials' },
      { id: 'alg1-quadratics', name: 'Quadratic Equations' },
    ],
  },
  {
    id: 'algebra-2',
    name: 'Algebra 2',
    icon: 'calculator',
    color: '#6C5CE7',
    topics: [
      { id: 'alg2-complex', name: 'Complex Numbers' },
      { id: 'alg2-polynomials', name: 'Polynomial Functions' },
      { id: 'alg2-rational', name: 'Rational Functions' },
      { id: 'alg2-exponential', name: 'Exponential & Logarithmic Functions' },
      { id: 'alg2-sequences', name: 'Sequences & Series' },
    ],
  },
  {
    id: 'geometry',
    name: 'Geometry',
    icon: 'shapes',
    color: '#00CEC9',
    topics: [
      { id: 'geo-triangles', name: 'Triangles & Congruence' },
      { id: 'geo-circles', name: 'Circles' },
      { id: 'geo-area-volume', name: 'Area & Volume' },
      { id: 'geo-transformations', name: 'Transformations' },
      { id: 'geo-proofs', name: 'Proofs & Reasoning' },
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    icon: 'leaf',
    color: '#00B894',
    topics: [
      { id: 'bio-cells', name: 'Cell Biology' },
      { id: 'bio-genetics', name: 'Genetics' },
      { id: 'bio-evolution', name: 'Evolution' },
      { id: 'bio-ecology', name: 'Ecology' },
      { id: 'bio-human-body', name: 'Human Body Systems' },
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    icon: 'flask',
    color: '#00CEC9',
    topics: [
      { id: 'chem-matter', name: 'Matter & Atomic Theory' },
      { id: 'chem-periodic-table', name: 'Periodic Table' },
      { id: 'chem-bonding', name: 'Chemical Bonding' },
      { id: 'chem-reactions', name: 'Chemical Reactions' },
      { id: 'chem-stoichiometry', name: 'Stoichiometry' },
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    icon: 'atom',
    color: '#0984E3',
    topics: [
      { id: 'phys-motion', name: 'Motion & Forces' },
      { id: 'phys-energy', name: 'Energy & Work' },
      { id: 'phys-waves', name: 'Waves & Optics' },
      { id: 'phys-electricity', name: 'Electricity & Magnetism' },
      { id: 'phys-thermo', name: 'Thermodynamics' },
    ],
  },
  {
    id: 'us-history',
    name: 'US History',
    icon: 'flag',
    color: '#D63031',
    topics: [
      { id: 'ush-colonial', name: 'Colonial Period' },
      { id: 'ush-revolution', name: 'American Revolution' },
      { id: 'ush-civil-war', name: 'Civil War' },
      { id: 'ush-20th-century', name: '20th Century' },
      { id: 'ush-modern', name: 'Modern America' },
    ],
  },
  {
    id: 'world-history',
    name: 'World History',
    icon: 'globe',
    color: '#E17055',
    topics: [
      { id: 'wh-ancient', name: 'Ancient Civilizations' },
      { id: 'wh-medieval', name: 'Medieval Period' },
      { id: 'wh-renaissance', name: 'Renaissance & Reformation' },
      { id: 'wh-modern', name: 'Modern World' },
    ],
  },
  {
    id: 'statistics',
    name: 'Statistics',
    icon: 'bar-chart',
    color: '#636E72',
    topics: [
      { id: 'stats-descriptive', name: 'Descriptive Statistics' },
      { id: 'stats-probability', name: 'Probability' },
      { id: 'stats-distributions', name: 'Distributions' },
      { id: 'stats-inference', name: 'Statistical Inference' },
      { id: 'stats-regression', name: 'Regression' },
    ],
  },
  {
    id: 'computer-science',
    name: 'Computer Science',
    icon: 'code',
    color: '#2D3436',
    topics: [
      { id: 'cs-algorithms', name: 'Algorithms' },
      { id: 'cs-data-structures', name: 'Data Structures' },
      { id: 'cs-programming', name: 'Programming Fundamentals' },
      { id: 'cs-web', name: 'Web Development' },
      { id: 'cs-databases', name: 'Databases' },
    ],
  },
  {
    id: 'spanish',
    name: 'Spanish',
    icon: 'language',
    color: '#E84393',
    topics: [
      { id: 'span-grammar', name: 'Grammar' },
      { id: 'span-vocabulary', name: 'Vocabulary' },
      { id: 'span-reading', name: 'Reading Comprehension' },
      { id: 'span-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'french',
    name: 'French',
    icon: 'language',
    color: '#0984E3',
    topics: [
      { id: 'fr-grammar', name: 'Grammar' },
      { id: 'fr-vocabulary', name: 'Vocabulary' },
      { id: 'fr-reading', name: 'Reading Comprehension' },
      { id: 'fr-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'economics',
    name: 'Economics',
    icon: 'trending-up',
    color: '#FDCB6E',
    topics: [
      { id: 'econ-micro', name: 'Microeconomics' },
      { id: 'econ-macro', name: 'Macroeconomics' },
      { id: 'econ-supply-demand', name: 'Supply & Demand' },
      { id: 'econ-fiscal', name: 'Fiscal & Monetary Policy' },
    ],
  },
  {
    id: 'english',
    name: 'English',
    icon: 'book',
    color: '#FDCB6E',
    topics: [
      { id: 'eng-grammar', name: 'Grammar & Usage' },
      { id: 'eng-reading', name: 'Reading Comprehension' },
      { id: 'eng-writing', name: 'Writing Skills' },
      { id: 'eng-literature', name: 'Literature Analysis' },
      { id: 'eng-vocabulary', name: 'Vocabulary' },
    ],
  },
];
