export interface SubjectTopic {
  id: string;
  name: string;
}

export interface SubjectUnit {
  id: string;
  name: string;
}

export interface Subject {
  id: string;
  name: string;
  icon: string;
  color: string;
  coverImage: string;
  topics: SubjectTopic[];
  units?: SubjectUnit[];
}

export const subjects: Subject[] = [
  {
    id: 'sat',
    name: 'SAT',
    icon: 'school',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b6f71?w=600&q=80',
    topics: [
      { id: 'sat-reading', name: 'Reading Comprehension' },
      { id: 'sat-writing', name: 'Writing & Language' },
      { id: 'sat-math-no-calc', name: 'Math (No Calculator)' },
      { id: 'sat-math-calc', name: 'Math (Calculator)' },
      { id: 'sat-grammar', name: 'Grammar & Usage' },
      { id: 'sat-vocabulary', name: 'Vocabulary in Context' },
      { id: 'sat-data-analysis', name: 'Data Analysis' },
      { id: 'sat-algebra', name: 'Heart of Algebra' },
      { id: 'sat-advanced-math', name: 'Passport to Advanced Math' },
    ],
  },
  {
    id: 'act',
    name: 'ACT',
    icon: 'school',
    color: '#E84393',
    coverImage: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600&q=80',
    topics: [
      { id: 'act-english', name: 'English' },
      { id: 'act-math', name: 'Mathematics' },
      { id: 'act-reading', name: 'Reading' },
      { id: 'act-science', name: 'Science' },
      { id: 'act-writing', name: 'Writing (Essay)' },
    ],
  },
  {
    id: 'ap-biology',
    name: 'AP Biology',
    icon: 'leaf',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1530026186672-2cd00ffc50fe?w=600&q=80',
    topics: [
      { id: 'ap-bio-cells', name: 'Cell Structure & Function' },
      { id: 'ap-bio-genetics', name: 'Genetics & Heredity' },
      { id: 'ap-bio-evolution', name: 'Evolution & Natural Selection' },
      { id: 'ap-bio-ecology', name: 'Ecology' },
      { id: 'ap-bio-molecular', name: 'Molecular Biology' },
      { id: 'ap-bio-physiology', name: 'Animal Physiology' },
      { id: 'ap-bio-plants', name: 'Plant Biology' },
    ],
  },
  {
    id: 'ap-chemistry',
    name: 'AP Chemistry',
    icon: 'flask',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&q=80',
    topics: [
      { id: 'ap-chem-atomic', name: 'Atomic Structure' },
      { id: 'ap-chem-bonding', name: 'Chemical Bonding' },
      { id: 'ap-chem-reactions', name: 'Chemical Reactions' },
      { id: 'ap-chem-kinetics', name: 'Kinetics' },
      { id: 'ap-chem-thermo', name: 'Thermodynamics' },
      { id: 'ap-chem-equilibrium', name: 'Equilibrium' },
      { id: 'ap-chem-acids', name: 'Acids & Bases' },
    ],
  },
  {
    id: 'ap-physics-1',
    name: 'AP Physics 1',
    icon: 'atom',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
    topics: [
      { id: 'ap-phys1-kinematics', name: 'Kinematics' },
      { id: 'ap-phys1-dynamics', name: 'Dynamics (Forces)' },
      { id: 'ap-phys1-energy', name: 'Energy & Work' },
      { id: 'ap-phys1-momentum', name: 'Momentum' },
      { id: 'ap-phys1-rotation', name: 'Rotational Motion' },
      { id: 'ap-phys1-waves', name: 'Waves & Sound' },
      { id: 'ap-phys1-circuits', name: 'Simple Circuits' },
    ],
  },
  {
    id: 'ap-us-history',
    name: 'AP US History',
    icon: 'flag',
    color: '#D63031',
    coverImage: 'https://images.unsplash.com/photo-1501139083538-0139583c060f?w=600&q=80',
    topics: [
      { id: 'ap-ush-colonial', name: 'Colonial America' },
      { id: 'ap-ush-revolution', name: 'American Revolution' },
      { id: 'ap-ush-constitution', name: 'Constitution & Early Republic' },
      { id: 'ap-ush-civil-war', name: 'Civil War & Reconstruction' },
      { id: 'ap-ush-gilded', name: 'Gilded Age & Progressive Era' },
      { id: 'ap-ush-wwi-wwii', name: 'World Wars' },
      { id: 'ap-ush-cold-war', name: 'Cold War Era' },
      { id: 'ap-ush-modern', name: 'Modern America' },
    ],
  },
  {
    id: 'ap-world-history',
    name: 'AP World History',
    icon: 'globe',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=600&q=80',
    topics: [
      { id: 'ap-wh-ancient', name: 'Ancient Civilizations' },
      { id: 'ap-wh-classical', name: 'Classical Era' },
      { id: 'ap-wh-medieval', name: 'Medieval Period' },
      { id: 'ap-wh-early-modern', name: 'Early Modern Period' },
      { id: 'ap-wh-industrialization', name: 'Industrialization' },
      { id: 'ap-wh-modern', name: 'Modern Era' },
    ],
  },
  {
    id: 'ap-psychology',
    name: 'AP Psychology',
    icon: 'brain',
    color: '#A29BFE',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    topics: [
      { id: 'ap-psych-bio', name: 'Biological Bases of Behavior' },
      { id: 'ap-psych-sensation', name: 'Sensation & Perception' },
      { id: 'ap-psych-learning', name: 'Learning & Memory' },
      { id: 'ap-psych-cognition', name: 'Cognition' },
      { id: 'ap-psych-development', name: 'Developmental Psychology' },
      { id: 'ap-psych-abnormal', name: 'Abnormal Psychology' },
      { id: 'ap-psych-social', name: 'Social Psychology' },
    ],
  },
  {
    id: 'ap-english-lang',
    name: 'AP English Language',
    icon: 'book',
    color: '#FDCB6E',
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=600&q=80',
    topics: [
      { id: 'ap-eng-rhetoric', name: 'Rhetorical Analysis' },
      { id: 'ap-eng-argument', name: 'Argumentation' },
      { id: 'ap-eng-synthesis', name: 'Synthesis' },
      { id: 'ap-eng-style', name: 'Style & Tone' },
    ],
  },
  {
    id: 'ap-calculus-ab',
    name: 'AP Calculus AB',
    icon: 'calculator',
    color: '#74B9FF',
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=600&q=80',
    topics: [
      { id: 'ap-calc-limits', name: 'Limits & Continuity' },
      { id: 'ap-calc-derivatives', name: 'Derivatives' },
      { id: 'ap-calc-integrals', name: 'Integrals' },
      { id: 'ap-calc-applications', name: 'Applications of Derivatives' },
      { id: 'ap-calc-ftc', name: 'Fundamental Theorem of Calculus' },
    ],
  },
  {
    id: 'algebra-1',
    name: 'Algebra 1',
    icon: 'calculator',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?w=600&q=80',
    topics: [
      { id: 'alg1-linear', name: 'Linear Equations' },
      { id: 'alg1-inequalities', name: 'Inequalities' },
      { id: 'alg1-systems', name: 'Systems of Equations' },
      { id: 'alg1-polynomials', name: 'Polynomials' },
      { id: 'alg1-quadratics', name: 'Quadratic Equations' },
    ],
  },
  {
    id: 'algebra-2',
    name: 'Algebra 2',
    icon: 'calculator',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&q=80',
    topics: [
      { id: 'alg2-complex', name: 'Complex Numbers' },
      { id: 'alg2-polynomials', name: 'Polynomial Functions' },
      { id: 'alg2-rational', name: 'Rational Functions' },
      { id: 'alg2-exponential', name: 'Exponential & Logarithmic Functions' },
      { id: 'alg2-sequences', name: 'Sequences & Series' },
    ],
  },
  {
    id: 'geometry',
    name: 'Geometry',
    icon: 'shapes',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&q=80',
    topics: [
      { id: 'geo-triangles', name: 'Triangles & Congruence' },
      { id: 'geo-circles', name: 'Circles' },
      { id: 'geo-area-volume', name: 'Area & Volume' },
      { id: 'geo-transformations', name: 'Transformations' },
      { id: 'geo-proofs', name: 'Proofs & Reasoning' },
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    icon: 'leaf',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
    topics: [
      { id: 'bio-cells', name: 'Cell Biology' },
      { id: 'bio-genetics', name: 'Genetics' },
      { id: 'bio-evolution', name: 'Evolution' },
      { id: 'bio-ecology', name: 'Ecology' },
      { id: 'bio-human-body', name: 'Human Body Systems' },
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    icon: 'flask',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1507668339897-8a035aa9527d?w=600&q=80',
    topics: [
      { id: 'chem-matter', name: 'Matter & Atomic Theory' },
      { id: 'chem-periodic-table', name: 'Periodic Table' },
      { id: 'chem-bonding', name: 'Chemical Bonding' },
      { id: 'chem-reactions', name: 'Chemical Reactions' },
      { id: 'chem-stoichiometry', name: 'Stoichiometry' },
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    icon: 'atom',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1617791160536-598cf32026fb?w=600&q=80',
    topics: [
      { id: 'phys-motion', name: 'Motion & Forces' },
      { id: 'phys-energy', name: 'Energy & Work' },
      { id: 'phys-waves', name: 'Waves & Optics' },
      { id: 'phys-electricity', name: 'Electricity & Magnetism' },
      { id: 'phys-thermo', name: 'Thermodynamics' },
    ],
  },
  {
    id: 'us-history',
    name: 'US History',
    icon: 'flag',
    color: '#D63031',
    coverImage: 'https://images.unsplash.com/photo-1508812676971-bc3f3aa24da0?w=600&q=80',
    topics: [
      { id: 'ush-colonial', name: 'Colonial Period' },
      { id: 'ush-revolution', name: 'American Revolution' },
      { id: 'ush-civil-war', name: 'Civil War' },
      { id: 'ush-20th-century', name: '20th Century' },
      { id: 'ush-modern', name: 'Modern America' },
    ],
  },
  {
    id: 'world-history',
    name: 'World History',
    icon: 'globe',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1461360370896-922624d12aa1?w=600&q=80',
    topics: [
      { id: 'wh-ancient', name: 'Ancient Civilizations' },
      { id: 'wh-medieval', name: 'Medieval Period' },
      { id: 'wh-renaissance', name: 'Renaissance & Reformation' },
      { id: 'wh-modern', name: 'Modern World' },
    ],
  },
  {
    id: 'statistics',
    name: 'Statistics',
    icon: 'bar-chart',
    color: '#636E72',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    topics: [
      { id: 'stats-descriptive', name: 'Descriptive Statistics' },
      { id: 'stats-probability', name: 'Probability' },
      { id: 'stats-distributions', name: 'Distributions' },
      { id: 'stats-inference', name: 'Statistical Inference' },
      { id: 'stats-regression', name: 'Regression' },
    ],
  },
  {
    id: 'computer-science',
    name: 'Computer Science',
    icon: 'code',
    color: '#2D3436',
    coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&q=80',
    topics: [
      { id: 'cs-algorithms', name: 'Algorithms' },
      { id: 'cs-data-structures', name: 'Data Structures' },
      { id: 'cs-programming', name: 'Programming Fundamentals' },
      { id: 'cs-web', name: 'Web Development' },
      { id: 'cs-databases', name: 'Databases' },
    ],
  },
  {
    id: 'spanish',
    name: 'Spanish',
    icon: 'language',
    color: '#E84393',
    coverImage: 'https://images.unsplash.com/photo-1543783207-ec64e4d95325?w=600&q=80',
    topics: [
      { id: 'span-grammar', name: 'Grammar' },
      { id: 'span-vocabulary', name: 'Vocabulary' },
      { id: 'span-reading', name: 'Reading Comprehension' },
      { id: 'span-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'french',
    name: 'French',
    icon: 'language',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80',
    topics: [
      { id: 'fr-grammar', name: 'Grammar' },
      { id: 'fr-vocabulary', name: 'Vocabulary' },
      { id: 'fr-reading', name: 'Reading Comprehension' },
      { id: 'fr-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'economics',
    name: 'Economics',
    icon: 'trending-up',
    color: '#FDCB6E',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
    topics: [
      { id: 'econ-micro', name: 'Microeconomics' },
      { id: 'econ-macro', name: 'Macroeconomics' },
      { id: 'econ-supply-demand', name: 'Supply & Demand' },
      { id: 'econ-fiscal', name: 'Fiscal & Monetary Policy' },
    ],
  },
  {
    id: 'english',
    name: 'English',
    icon: 'book',
    color: '#FDCB6E',
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80',
    topics: [
      { id: 'eng-grammar', name: 'Grammar & Usage' },
      { id: 'eng-reading', name: 'Reading Comprehension' },
      { id: 'eng-writing', name: 'Writing Skills' },
      { id: 'eng-literature', name: 'Literature Analysis' },
      { id: 'eng-vocabulary', name: 'Vocabulary' },
    ],
  },
  // Additional AP Courses
  {
    id: 'ap-calculus-bc',
    name: 'AP Calculus BC',
    icon: 'calculator',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&q=80',
    topics: [
      { id: 'ap-calcbc-limits', name: 'Limits & Continuity' },
      { id: 'ap-calcbc-derivatives', name: 'Derivatives' },
      { id: 'ap-calcbc-integrals', name: 'Integrals' },
      { id: 'ap-calcbc-series', name: 'Infinite Series' },
      { id: 'ap-calcbc-parametric', name: 'Parametric & Polar Equations' },
      { id: 'ap-calcbc-techniques', name: 'Advanced Integration Techniques' },
    ],
  },
  {
    id: 'ap-statistics',
    name: 'AP Statistics',
    icon: 'bar-chart',
    color: '#636E72',
    coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    topics: [
      { id: 'ap-stats-exploring', name: 'Exploring Data' },
      { id: 'ap-stats-sampling', name: 'Sampling & Experimentation' },
      { id: 'ap-stats-probability', name: 'Probability' },
      { id: 'ap-stats-distributions', name: 'Probability Distributions' },
      { id: 'ap-stats-inference', name: 'Statistical Inference' },
    ],
  },
  {
    id: 'ap-cs-a',
    name: 'AP Computer Science A',
    icon: 'code',
    color: '#2D3436',
    coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&q=80',
    topics: [
      { id: 'ap-csa-java', name: 'Java Fundamentals' },
      { id: 'ap-csa-oop', name: 'Object-Oriented Programming' },
      { id: 'ap-csa-arrays', name: 'Arrays & ArrayLists' },
      { id: 'ap-csa-inheritance', name: 'Inheritance & Polymorphism' },
      { id: 'ap-csa-recursion', name: 'Recursion & Algorithms' },
    ],
  },
  {
    id: 'ap-environmental-science',
    name: 'AP Environmental Science',
    icon: 'leaf',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80',
    topics: [
      { id: 'ap-envs-ecosystems', name: 'Ecosystems' },
      { id: 'ap-envs-biodiversity', name: 'Biodiversity & Evolution' },
      { id: 'ap-envs-energy', name: 'Energy Resources' },
      { id: 'ap-envs-pollution', name: 'Pollution & Remediation' },
      { id: 'ap-envs-climate', name: 'Global Change & Climate' },
    ],
  },
  {
    id: 'ap-gov',
    name: 'AP US Government',
    icon: 'flag',
    color: '#D63031',
    coverImage: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=600&q=80',
    topics: [
      { id: 'ap-gov-constitution', name: 'Constitutional Foundations' },
      { id: 'ap-gov-institutions', name: 'Branches of Government' },
      { id: 'ap-gov-civil-rights', name: 'Civil Liberties & Rights' },
      { id: 'ap-gov-political', name: 'Political Participation' },
      { id: 'ap-gov-policy', name: 'Public Policy' },
    ],
  },
  {
    id: 'ap-macroeconomics',
    name: 'AP Macroeconomics',
    icon: 'trending-up',
    color: '#FDCB6E',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
    topics: [
      { id: 'ap-macro-gdp', name: 'GDP & Economic Growth' },
      { id: 'ap-macro-unemployment', name: 'Unemployment & Inflation' },
      { id: 'ap-macro-fiscal', name: 'Fiscal Policy' },
      { id: 'ap-macro-monetary', name: 'Monetary Policy & Banking' },
      { id: 'ap-macro-trade', name: 'International Trade' },
    ],
  },
  {
    id: 'ap-microeconomics',
    name: 'AP Microeconomics',
    icon: 'trending-up',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80',
    topics: [
      { id: 'ap-micro-supply-demand', name: 'Supply & Demand' },
      { id: 'ap-micro-elasticity', name: 'Elasticity' },
      { id: 'ap-micro-market-structures', name: 'Market Structures' },
      { id: 'ap-micro-factor-markets', name: 'Factor Markets' },
      { id: 'ap-micro-market-failure', name: 'Market Failure & Externalities' },
    ],
  },
  {
    id: 'ap-human-geography',
    name: 'AP Human Geography',
    icon: 'globe',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=600&q=80',
    topics: [
      { id: 'ap-hug-population', name: 'Population & Migration' },
      { id: 'ap-hug-culture', name: 'Cultural Patterns' },
      { id: 'ap-hug-political', name: 'Political Geography' },
      { id: 'ap-hug-agriculture', name: 'Agriculture & Rural Land Use' },
      { id: 'ap-hug-urbanization', name: 'Cities & Urbanization' },
    ],
  },
  {
    id: 'ap-european-history',
    name: 'AP European History',
    icon: 'globe',
    color: '#A29BFE',
    coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600&q=80',
    topics: [
      { id: 'ap-euro-renaissance', name: 'Renaissance & Reformation' },
      { id: 'ap-euro-absolutism', name: 'Absolutism & Enlightenment' },
      { id: 'ap-euro-revolution', name: 'French Revolution & Napoleon' },
      { id: 'ap-euro-industrialization', name: 'Industrialization' },
      { id: 'ap-euro-world-wars', name: 'World Wars & Cold War' },
    ],
  },
  // More High School / College Prep
  {
    id: 'pre-calculus',
    name: 'Pre-Calculus',
    icon: 'calculator',
    color: '#74B9FF',
    coverImage: 'https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?w=600&q=80',
    topics: [
      { id: 'precalc-functions', name: 'Functions & Graphs' },
      { id: 'precalc-trig', name: 'Trigonometry' },
      { id: 'precalc-conics', name: 'Conic Sections' },
      { id: 'precalc-sequences', name: 'Sequences & Series' },
      { id: 'precalc-limits', name: 'Introduction to Limits' },
    ],
  },
  {
    id: 'trigonometry',
    name: 'Trigonometry',
    icon: 'shapes',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&q=80',
    topics: [
      { id: 'trig-unit-circle', name: 'Unit Circle' },
      { id: 'trig-functions', name: 'Trig Functions & Graphs' },
      { id: 'trig-identities', name: 'Trig Identities' },
      { id: 'trig-equations', name: 'Trig Equations' },
      { id: 'trig-applications', name: 'Applications & Law of Sines/Cosines' },
    ],
  },
  {
    id: 'middle-school-math',
    name: 'Middle School Math',
    icon: 'calculator',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?w=600&q=80',
    topics: [
      { id: 'ms-fractions', name: 'Fractions & Decimals' },
      { id: 'ms-ratios', name: 'Ratios & Proportions' },
      { id: 'ms-integers', name: 'Integers & Number Theory' },
      { id: 'ms-algebra', name: 'Introduction to Algebra' },
      { id: 'ms-geometry', name: 'Basic Geometry' },
    ],
  },
  // More Languages
  {
    id: 'german',
    name: 'German',
    icon: 'language',
    color: '#2D3436',
    coverImage: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=600&q=80',
    topics: [
      { id: 'de-grammar', name: 'Grammar & Cases' },
      { id: 'de-vocabulary', name: 'Vocabulary' },
      { id: 'de-reading', name: 'Reading Comprehension' },
      { id: 'de-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'mandarin',
    name: 'Mandarin Chinese',
    icon: 'language',
    color: '#D63031',
    coverImage: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=600&q=80',
    topics: [
      { id: 'zh-pinyin', name: 'Pinyin & Pronunciation' },
      { id: 'zh-characters', name: 'Characters (Hanzi)' },
      { id: 'zh-grammar', name: 'Grammar & Sentence Structure' },
      { id: 'zh-vocabulary', name: 'Vocabulary' },
    ],
  },
  {
    id: 'japanese',
    name: 'Japanese',
    icon: 'language',
    color: '#E84393',
    coverImage: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=600&q=80',
    topics: [
      { id: 'ja-hiragana-katakana', name: 'Hiragana & Katakana' },
      { id: 'ja-kanji', name: 'Kanji Basics' },
      { id: 'ja-grammar', name: 'Grammar & Particles' },
      { id: 'ja-vocabulary', name: 'Vocabulary' },
    ],
  },
  {
    id: 'latin',
    name: 'Latin',
    icon: 'book',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?w=600&q=80',
    topics: [
      { id: 'la-grammar', name: 'Grammar & Declensions' },
      { id: 'la-vocabulary', name: 'Vocabulary' },
      { id: 'la-translation', name: 'Translation & Prose' },
      { id: 'la-culture', name: 'Roman History & Culture' },
    ],
  },
  // Standardized Test Prep
  {
    id: 'gre',
    name: 'GRE',
    icon: 'school',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b6f71?w=600&q=80',
    topics: [
      { id: 'gre-verbal', name: 'Verbal Reasoning' },
      { id: 'gre-quantitative', name: 'Quantitative Reasoning' },
      { id: 'gre-vocabulary', name: 'Vocabulary' },
      { id: 'gre-writing', name: 'Analytical Writing' },
    ],
  },
  {
    id: 'gmat',
    name: 'GMAT',
    icon: 'school',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600&q=80',
    topics: [
      { id: 'gmat-verbal', name: 'Verbal Reasoning' },
      { id: 'gmat-quantitative', name: 'Quantitative Reasoning' },
      { id: 'gmat-integrated', name: 'Integrated Reasoning' },
      { id: 'gmat-writing', name: 'Analytical Writing' },
    ],
  },
  {
    id: 'mcat',
    name: 'MCAT',
    icon: 'school',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    topics: [
      { id: 'mcat-bio-biochem', name: 'Biology & Biochemistry' },
      { id: 'mcat-chem-physics', name: 'Chemistry & Physics' },
      { id: 'mcat-psych-soc', name: 'Psychology & Sociology' },
      { id: 'mcat-cars', name: 'Critical Analysis & Reasoning (CARS)' },
    ],
  },
  {
    id: 'lsat',
    name: 'LSAT',
    icon: 'school',
    color: '#D63031',
    coverImage: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=600&q=80',
    topics: [
      { id: 'lsat-logical', name: 'Logical Reasoning' },
      { id: 'lsat-analytical', name: 'Analytical Reasoning (Logic Games)' },
      { id: 'lsat-reading', name: 'Reading Comprehension' },
      { id: 'lsat-writing', name: 'LSAT Writing' },
    ],
  },
  {
    id: 'toefl',
    name: 'TOEFL',
    icon: 'school',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b6f71?w=600&q=80',
    topics: [
      { id: 'toefl-reading', name: 'Reading' },
      { id: 'toefl-listening', name: 'Listening' },
      { id: 'toefl-speaking', name: 'Speaking' },
      { id: 'toefl-writing', name: 'Writing' },
    ],
  },
  {
    id: 'ielts',
    name: 'IELTS',
    icon: 'school',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b6f71?w=600&q=80',
    topics: [
      { id: 'ielts-reading', name: 'Reading' },
      { id: 'ielts-listening', name: 'Listening' },
      { id: 'ielts-speaking', name: 'Speaking' },
      { id: 'ielts-writing', name: 'Writing' },
    ],
  },
  // AP (additional)
  {
    id: 'ap-physics-2',
    name: 'AP Physics 2',
    icon: 'atom',
    color: '#6C5CE7',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
    topics: [
      { id: 'ap-phys2-fluids', name: 'Fluids' },
      { id: 'ap-phys2-thermo', name: 'Thermodynamics' },
      { id: 'ap-phys2-electrostatics', name: 'Electrostatics' },
      { id: 'ap-phys2-magnetism', name: 'Magnetism' },
      { id: 'ap-phys2-optics', name: 'Optics & Modern Physics' },
    ],
  },
  {
    id: 'ap-physics-c',
    name: 'AP Physics C: Mechanics',
    icon: 'atom',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=600&q=80',
    topics: [
      { id: 'ap-physc-kinematics', name: 'Kinematics' },
      { id: 'ap-physc-newtons-laws', name: "Newton's Laws" },
      { id: 'ap-physc-energy', name: 'Energy & Work' },
      { id: 'ap-physc-rotation', name: 'Rotational Motion' },
      { id: 'ap-physc-oscillations', name: 'Oscillations & Gravity' },
    ],
  },
  {
    id: 'ap-art-history',
    name: 'AP Art History',
    icon: 'color-palette',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1501472312651-726afe119ff1?w=600&q=80',
    topics: [
      { id: 'ap-art-ancient', name: 'Ancient & Medieval Art' },
      { id: 'ap-art-renaissance', name: 'Renaissance Art' },
      { id: 'ap-art-modern', name: 'Modern & Contemporary Art' },
      { id: 'ap-art-non-western', name: 'Non-Western Art' },
      { id: 'ap-art-analysis', name: 'Visual Analysis & Criticism' },
    ],
  },
  {
    id: 'ap-cs-principles',
    name: 'AP Computer Science Principles',
    icon: 'code',
    color: '#2D3436',
    coverImage: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&q=80',
    topics: [
      { id: 'ap-csp-creativity', name: 'Creativity & Innovation' },
      { id: 'ap-csp-abstraction', name: 'Abstraction & Data' },
      { id: 'ap-csp-algorithms', name: 'Algorithms & Programming' },
      { id: 'ap-csp-internet', name: 'The Internet' },
      { id: 'ap-csp-security', name: 'Cybersecurity & Privacy' },
    ],
  },
  // College-level subjects
  {
    id: 'organic-chemistry',
    name: 'Organic Chemistry',
    icon: 'flask',
    color: '#E84393',
    coverImage: 'https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?w=600&q=80',
    topics: [
      { id: 'ochem-bonding', name: 'Bonding & Structure' },
      { id: 'ochem-nomenclature', name: 'Nomenclature' },
      { id: 'ochem-reactions', name: 'Reaction Mechanisms' },
      { id: 'ochem-stereochemistry', name: 'Stereochemistry' },
      { id: 'ochem-spectroscopy', name: 'Spectroscopy (NMR/IR)' },
    ],
  },
  {
    id: 'biochemistry',
    name: 'Biochemistry',
    icon: 'flask',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1530026186672-2cd00ffc50fe?w=600&q=80',
    topics: [
      { id: 'biochem-amino-acids', name: 'Amino Acids & Proteins' },
      { id: 'biochem-enzymes', name: 'Enzymes & Kinetics' },
      { id: 'biochem-metabolism', name: 'Metabolism & Energy' },
      { id: 'biochem-dna-rna', name: 'DNA, RNA & Transcription' },
      { id: 'biochem-lipids', name: 'Lipids & Membranes' },
    ],
  },
  {
    id: 'microbiology',
    name: 'Microbiology',
    icon: 'leaf',
    color: '#00CEC9',
    coverImage: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=600&q=80',
    topics: [
      { id: 'micro-bacteria', name: 'Bacterial Structure & Growth' },
      { id: 'micro-viruses', name: 'Viruses & Replication' },
      { id: 'micro-fungi', name: 'Fungi & Parasites' },
      { id: 'micro-immune', name: 'Immune System' },
      { id: 'micro-genetics', name: 'Microbial Genetics' },
    ],
  },
  {
    id: 'anatomy-physiology',
    name: 'Anatomy & Physiology',
    icon: 'body',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=600&q=80',
    topics: [
      { id: 'anat-skeletal', name: 'Skeletal & Muscular Systems' },
      { id: 'anat-nervous', name: 'Nervous System' },
      { id: 'anat-cardiovascular', name: 'Cardiovascular System' },
      { id: 'anat-respiratory', name: 'Respiratory System' },
      { id: 'anat-digestive', name: 'Digestive & Endocrine Systems' },
    ],
  },
  {
    id: 'linear-algebra',
    name: 'Linear Algebra',
    icon: 'calculator',
    color: '#A29BFE',
    coverImage: 'https://images.unsplash.com/photo-1635070041409-e63e783ce3c1?w=600&q=80',
    topics: [
      { id: 'linalg-vectors', name: 'Vectors & Vector Spaces' },
      { id: 'linalg-matrices', name: 'Matrices & Operations' },
      { id: 'linalg-determinants', name: 'Determinants' },
      { id: 'linalg-eigenvalues', name: 'Eigenvalues & Eigenvectors' },
      { id: 'linalg-transformations', name: 'Linear Transformations' },
    ],
  },
  {
    id: 'discrete-mathematics',
    name: 'Discrete Mathematics',
    icon: 'calculator',
    color: '#636E72',
    coverImage: 'https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=600&q=80',
    topics: [
      { id: 'discrete-logic', name: 'Logic & Propositional Calculus' },
      { id: 'discrete-sets', name: 'Sets & Functions' },
      { id: 'discrete-proofs', name: 'Proofs & Induction' },
      { id: 'discrete-graph-theory', name: 'Graph Theory' },
      { id: 'discrete-combinatorics', name: 'Combinatorics & Counting' },
    ],
  },
  // Languages (additional)
  {
    id: 'italian',
    name: 'Italian',
    icon: 'language',
    color: '#E17055',
    coverImage: 'https://images.unsplash.com/photo-1515542622106-078bda21e50f?w=600&q=80',
    topics: [
      { id: 'it-grammar', name: 'Grammar' },
      { id: 'it-vocabulary', name: 'Vocabulary' },
      { id: 'it-reading', name: 'Reading Comprehension' },
      { id: 'it-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'portuguese',
    name: 'Portuguese',
    icon: 'language',
    color: '#00B894',
    coverImage: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=600&q=80',
    topics: [
      { id: 'pt-grammar', name: 'Grammar' },
      { id: 'pt-vocabulary', name: 'Vocabulary' },
      { id: 'pt-reading', name: 'Reading Comprehension' },
      { id: 'pt-conjugation', name: 'Verb Conjugation' },
    ],
  },
  {
    id: 'korean',
    name: 'Korean',
    icon: 'language',
    color: '#0984E3',
    coverImage: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=600&q=80',
    topics: [
      { id: 'ko-hangul', name: 'Hangul & Pronunciation' },
      { id: 'ko-grammar', name: 'Grammar & Particles' },
      { id: 'ko-vocabulary', name: 'Vocabulary' },
      { id: 'ko-reading', name: 'Reading Comprehension' },
    ],
  },
  {
    id: 'arabic',
    name: 'Arabic',
    icon: 'language',
    color: '#FDCB6E',
    coverImage: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=600&q=80',
    topics: [
      { id: 'ar-alphabet', name: 'Alphabet & Script' },
      { id: 'ar-grammar', name: 'Grammar & Morphology' },
      { id: 'ar-vocabulary', name: 'Vocabulary' },
      { id: 'ar-reading', name: 'Reading Comprehension' },
    ],
  },
];
